
### Create a user
POST http://localhost:3000/api/users
Content-Type: application.application/json

{
    "first_name": "Wendy",
    "last_name": "Lu",
    "phone": "84742742",
    "email": "Wendy@example.com",
    "address": "carry",
    "password": "securepassword"
}